### ISSUE TITLE
Debugger不会用

### ISSUE THREAD

**Issue by Liyunfan1998** [java-a/lab3#2]
Debugger
 is a program that facilitates debugging.
You can use a debugger to
Execute a single statement at a time.
Trace into or stepping over a method.
Set breakpoints.
Display variables.
Display call stack.
Modify variables.

**Comment by zhongyi-tong** [comment]
Debugger 在 比较后面的 lab 课中会介绍。建议你先学会 IDE（IntelliJ IDEA） 的基本使用，然后再来看 debugger 。像我们目前代码比较简短，你可以人脑思考一下每行执行完了之后变量发生了哪些变化。
